version: '3'

services:
    db:
        container_name: dictionary
        image: mysql
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: test
    adminer: 
        image: adminer
        restart: always
        ports:
            - 8080:8080
    gosql:
        build: .
        ports: 
            - "5000:5000"
        image: gosql:1.0
    
